input_paths:
  # student info
  utatg_roster: ../2024-Data/roster.csv
  quercus_gradebook: ../2024-Data/gradebook.csv

  # learning standards
  standards_lookup_table: ../2024-Data/standards_lookup_table.xlsx

  # assessments
  tutorial_glob: ../2024-Data/TUTData/PROCESSED/*/*_SBG.csv
  webwork_glob: ../2024-Data/WW/*.csv
  midterm_glob: ../2024-Data/*Midterm*/*.csv

  # manual overrides
  manual_scores: ../2024-Data/manual_scores.xlsx

output_dir: ../2024-Output
